/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "deep-navy": "#00000080",
        "near-black": "#00000080",
        "light-cool-grey": "#ffffff",
        "tedx-red": "#E10600",
        "electric-blue": "#E10600",
        "surface": "transparent",
        "surface-dim": "#00000080",
        "surface-bright": "#0A0A0A80",
        "surface-container-lowest": "#00000080",
        "surface-container-low": "#09090B80",
        "surface-container": "#12121280",
        "surface-container-high": "#18181B80",
        "surface-container-highest": "#27272A80",
        "surface-variant": "#18181B80",
        "on-surface": "#ffffff",
        "on-surface-variant": "#ffffff",
        "inverse-surface": "#ffffff",
        "inverse-on-surface": "#ffffff",
        "inverse-primary": "#E10600",
        "background": "transparent",
        "on-background": "#ffffff",
        "primary": "#E10600",
        "on-primary": "#ffffff",
        "primary-container": "#990400",
        "on-primary-container": "#ffffff",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb4ab",
        "on-primary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#ffffff",
        "secondary": "#E10600",
        "on-secondary": "#ffffff",
        "secondary-container": "#1E3A8A",
        "on-secondary-container": "#ffffff",
        "secondary-fixed": "#ffdbca",
        "secondary-fixed-dim": "#ffb68f",
        "on-secondary-fixed": "#ffffff",
        "on-secondary-fixed-variant": "#ffffff",
        "tertiary": "#E10600",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7d553c",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#ffdbc8",
        "tertiary-fixed-dim": "#f0bb9c",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary-fixed-variant": "#ffffff",
        "error": "#E10600",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#ffffff",
        "outline": "#27272A",
        "outline-variant": "#18181B",
        "surface-tint": "#E10600"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-lg": "1.5rem",
        margin: "4rem",
        gutter: "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "display-hero": ["Syne"],
        "label-md": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-badge": ["Plus Jakarta Sans"],
        "headline-lg": ["Syne"],
        "display-section": ["Syne"],
        "body-md": ["Inter"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "80px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-section": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    }
  }
}
